= Location finder
A small example to show how we can user serverless to reverse geocode a latitude/longitude. This example 
could be deployed on any serverless platform, the instructions here will help to deploy it on OpenWhisk

== Pre-requisites

* Access to OpenWhisk serverless platform
* OpenWhisk CLI configured for the platform
* Google Maps API Key 

== Build and Deploy

1. Copy `template.local.env` to `.env`
2. Update the env variables as needed

=== Build

Create the package to deploy function 

[code,sh]
----
npm run create-package
----

Build the nodejs application 

[code,sh]
----
npm run build
----

Deploy the function to OpenWhisk

[code,sh]
----
npm run deploy
----

Test the function 

[code,sh]
----
npm run dev
----

The above command should return you a response like:

[code,json]
----
{
  "location": "New Row, London WC2N 4LH, UK",
  "status": "OK"
}
----

=== API

If OpenWhisk API Gateway is deployed then we can create the REST API for action:

[code,json]
----
wsk -i  api create  /my /location get redhat-developers/location-finder <1>
wsk -i  api list  <2>
----

<1> create the API with base path as `my` and API path as `location` with HTTP verb as `get`
<2> This will list the APIs that are available in API Gateway and the URL which can be used to invoke it

==== Calling API 

[code,json]
----
curl -H "Content-Type: application/json" -X GET  -d '{"coords":{"lat":"51.5121378","lng":"-0.1269017"}}' [URL from above]
----

The command above should return the same response as above